### PR TITLE
Update Distributions.jl in Project.toml

### PR DESCRIPTION
**Pull request by juliohm**
Dear @kramsretlow , could you please review/merge this PR? It bumps the version of Distributions.jl.

I am starting to work on #3 , but first we need to update the package to the latest versions of some dependencies.

### CODE REVIEW

**Comment by juliohm** [comment]
@kramsretlow could you please take a look at this? Also, I would like to take this opportunity and ask if you would like to join efforts in this spatial statistics frontier. We've created an organization for statistic research in Earth sciences, and your package fits really well there. I could send ou an invitation if you are interested, and we could develop this package further from there.

My next plan is to submit a PR here to add integration with GeoStats.jl as we discussed in #3 . Appreciate if you can share your thoughts about the organisation invitation and this integration plan. The plan is to create a spatial solver that sets up the ALRsimple instance and runs it on spatial data types.

**Comment by kramsretlow** [comment]
I am merging this change, and afterwards I'll try to figure out why the checks are failing (also bump the levels on some of the other dependencies...)

@juliohm I am pleased to get your invitation to the organization, please do send it. Though I have to apologize again that I might not have a lot of time to help out.  The motivation to continue working on this topic is definitely there, though. I'll do what I can.

About GeoStats.jl integration, I am also very interested in principle.  I foresee some complications though, because at present Autologistic.jl doesn't include any specific functionality for fitting or prediction in partially-observed spatial fields (which I think is a key interest of GeoStats.jl).  The reason such functions aren't in there is that it's hard to do for these binary random fields!  Looking at it positively, if we can add anything useful for that case, it would be a big improvement.

In any case the best way to see what can be done is to try.  Please do as you've suggested, and I appreciate the opportunity to be involved.

**Comment by juliohm** [comment]
That is great @kramsretlow , thanks for merging, and for addressing the questions. I will send you the invitation to the organization, and then we can figure out how we could possibly migrate the repo there with you as the owner.

The integration idea will start with with we are calling *geostatistical learning problems*: https://juliaearth.github.io/GeoStats.jl/latest/userguide/ We can load any non-spatial learning model from the MLJ.jl framework, and use it directly with spatial data already. You can see in that user guide that we wrap the model in a `PointwiseLearn` which is just the simplest strategy possible to perform learning with non-spatial models (i.e. apply it pointwise). For autologistic regression, we need a separate learning solver (e.g. AutologisticRegression) that will take the coordinates of the spatial data into account. I will prepare a PR with this idea so that you can take a look.

The future contribution as you mentioned would be to consider partial observations. This is a more general problem that I am planning to tackle in the future as well, it is not defined in the framework yet. We only have three types of problems defined: Estimation, Simulation, Learning. The problem you describe is a combination of Estimation + Learning, and we can brainstorm several general methods to addressing it.

**Comment by juliohm** [comment]
Sent you the invitation to the organization. Appreciate if you can follow the instructions there like making your membership public, etc.

How we could migrate the repo to the org? Would you like to transfer it to me, and I take care of moving it there, and readjusting the URLs in the General registry? You don't need to worry about the current URL because GitHub redirects URLs when repos are transferred to other accounts or organizations.

**Comment by kramsretlow** [comment]
Hi @juliohm, just wanted to mention that I was happy to see CoDa.jl in the organization. I'm currently very interested in compositional data analysis as I'm working in the chemical industry with design & analysis of experiments involving compositions.  So perhaps over time I can contribute there as well.  I need to become familiar with the packages.

About migrating Autologistic.jl, I'm out of energy for today so please let me think about it more in the coming days. I suppose I don't mind transferring it for the purposes of moving it, assuming I will ultimately retain ownership over the package. I don't have lots of experience with this kind of thing so I'm not sure I grasp everything I should.   Also it might be prudent for both of us to work a little on the integration first to make sure it's actually a good fit.  Looking forward to collaboration!

**Comment by juliohm** [comment]
> Hi @juliohm, just wanted to mention that I was happy to see CoDa.jl in the organization. I'm currently very interested in compositional data analysis as I'm working in the chemical industry with design & analysis of experiments involving compositions. So perhaps over time I can contribute there as well. I need to become familiar with the packages. 

Awesome. Not many people have the background to work with this type of math, but I am sure you have a lot of background :) The basic ingredients are there, but we still need plot recipes for ternary plots, and other common statistical analysis tools.

> About migrating Autologistic.jl, I'm out of energy for today so please let me think about it more in the coming days. I suppose I don't mind transferring it for the purposes of moving it, assuming I will ultimately retain ownership over the package. I don't have lots of experience with this kind of thing so I'm not sure I grasp everything I should. Also it might be prudent for both of us to work a little on the integration first to make sure it's actually a good fit. Looking forward to collaboration!

It sounds great to me. The ideia is to just keep working on it in the organization to attract more contributors. I've noticed that keeping a repo in a personal account inhibits people from contributing for some reason. They think they are writing code to help improve someone else's profile on GitHub. You would still be the owner with all the access you have today. Let's work from here if you feel it is more comfortable for now, and we can reconsider this migration in the future. I am sure it is a good fit because spatial statistics is a big chunk of the JuliaEarth organization. The organization is really for advanced statistics research dealing with real-world Earth data, which is compositional, spatial, and so on... A really good research that could come out of this collaboration is the spatial regression of binary outcomes with compositional covariates. It is on the roadmap, but time is limited to develop all the ingredients. Your help is more than welcome :)

**Comment by juliohm** [comment]
I have a better idea regarding the migration of the the package to the organization. Since there are places for improvement that will require major refactoring of the code, I think it makes sense to start a new package afresh in the organization with a more organized API. What do you think? I will try to find time to read the paper and the code carefully, and will come back with a proposal. After that, we can start rewriting things in a more extensible Julian manner.

Thanks again for the feedback so far.

**Comment by kramsretlow** [comment]
Thanks for your comments.  It sounds prudent to do some investigation first and then decide how to proceed.  I'm certainly not against having the package (or some refactored successor) in the GeoStats organization.  And I agree with you about the reputability boost that comes with having repositories as part of an organization 😄 

About refactoring, while I am very open to suggestions for improvement, I have to say I spent a long time thinking about the architecture of the package.  I tried to arrange the types within the package so that I could cover all of the existing variants of the ALR model while also making it easy to extend the package to different ways of parametrizing the model.  Undoubtedly it could be improved, but it's not just code that's been thrown together without forethought.

The design of the package is more oriented toward being flexible to cover a lot of model alternatives than on having a very straightforward API for applying a specific variant.  That just reflects the fact that my original plan was to keep working on different extensions of this model.

At the time I wrote the package I thought it would be nice if the autologistic model (without regression/covariates part) could be made part of Distributions.jl, since it's just a multivariate discrete distribution. Similarly, I thought it would be nice if the autologistic regression model could follow the conventions of StatsModels.jl.  In the end, I decided not to pursue these ideas because I didn't think I could match the interfaces of those packages very well and still get what I needed. E.g. autologistic models are only defined up to an intractable normalizing constant, so some of the basic methods like `mean` or ` _loglikelihood` require sampling; similarly standard errors can't be straightforwardly computed, residuals are not well defined, etc.

I'm just giving you these comments so you can get a feeling for my design goals with the package. I'm very open to ideas about how the package could be made better and/or more "Julian."   If we fixed some aspects of the model, e.g. using the "simple" ALR model with a lattice graph, fixed (-1, +1) coding, and Gibbs sampling, then undoubtedly we could make things a lot simpler.  Maybe doing so for one or two model types would be sufficient for GeoStats.jl?

Curious to hear any ideas you have.

**Comment by juliohm** [comment]
> About refactoring, while I am very open to suggestions for improvement, I have to say I spent a long time thinking about the architecture of the package. I tried to arrange the types within the package so that I could cover all of the existing variants of the ALR model while also making it easy to extend the package to different ways of parametrizing the model. Undoubtedly it could be improved, but it's not just code that's been thrown together without forethought.

Of course! I definitely see this reflected in the code. I think there are places for improvement, particularly regarding the transfer of the learned model to a new domain. We need to be able to expose an API for end users that is as simple as a `fit/predict` workflow for regression for example, with additional details about the graph structure, and possibly other layers of abstraction regarding spatial domains. I totally agree that we should keep things general, and only provide additional functionality on a per-model basis (e.g. ALR).

> The design of the package is more oriented toward being flexible to cover a lot of model alternatives than on having a very straightforward API for applying a specific variant. That just reflects the fact that my original plan was to keep working on different extensions of this model.

I fully support this goal :) I like generality A LOT. We need to be able to write something that is composable, extensible, and with a nice API for specific cases.

> E.g. autologistic models are only defined up to an intractable normalizing constant, so some of the basic methods like `mean` or ` _loglikelihood` require sampling; similarly standard errors can't be straightforwardly computed, residuals are not well defined, etc.

I really like these technical details 💯 . Thank you for working on the package, and for brainstorming these possibilities of improvement.

> If we fixed some aspects of the model, e.g. using the "simple" ALR model with a lattice graph, fixed (-1, +1) coding, and Gibbs sampling, then undoubtedly we could make things a lot simpler. Maybe doing so for one or two model types would be sufficient for GeoStats.jl?

I think we have a long road of development to integrate the autologistic models approach to solving spatial problems like simulation, and learning problems. I am trying to fix some other things first in the project like being able to do spatial statistics on general meshes, and then will come back to study your work in more depth. Meanwhile, feel free to share your thoughts or any updates with your research. Looking forward to learning more. Really interesting work and approach.

**Comment by kramsretlow** [comment]
Thank you for your comments. I think we are basically on the same page. I guess my to-do item is to get more familiar with the way GeoStats.jl works; after that I might have something more concrete to say about how best to get an autologistic model into the framework. (Writing that sentence reminded me that there are probably alternative approaches for spatially-referenced binary responses, are you aware of any? maybe something like logit of a probability field = Gaussian process? I seem to recall one method involving thresholding a GP to get binary responses...)

I'll keep this topic in the back of my mind and poke at it if I have time. If I have any ideas or progress I'll let you know (same goes for CoDa).

**Comment by juliohm** [comment]
> Thank you for your comments. I think we are basically on the same page. I
> guess my to-do item is to get more familiar with the way GeoStats.jl works;
> after that I might have something more concrete to say about how best to
> get an autologistic model into the framework. (Writing that sentence
> reminded me that there are probably alternative approaches for
> spatially-referenced binary responses, are you aware of any? maybe
> something like logit of a probability field = Gaussian process? I seem to
> recall one method involving thresholding a GP to get binary responses...)
>

Thank you for taking the time to learn the framework. Many things will
change regarding the spatial data types currently defined but this will
only happen in the next minor release. I'm looking forward to brainstorming
ideas.

In the geostatistics literature I think the most popular method for
categorical response is indicator kriging. It works on thresholds as you
mentioned.


> I'll keep this topic in the back of my mind and poke at it if I have time.
> If I have any ideas or progress I'll let you know (same goes for CoDa).
>

That is great. Please let me know if I can be of any help.

>

**Pull request merged**
